define([], function () {
  return {
    PropertyPane: {
      AdvancedGroupName: 'Advanced',
      CategoryTitleFieldLabel: 'Group by category title',
      DefaultIconLabel: 'Default icon',
      DescriptionPlaceholder: 'Add description...',
      GeneralGroupName: 'General',
      GroupByCategoryLabel: 'Group by category',
      HeaderDescription: 'Configuration of the web part',
      MandatoryLinksLabel: 'Title and description for \'Mandatory links\'',
      RecommendedLinksLabel: 'Title and description for \'Recommended links\'',
      SelectDefaultIconLabel: 'Select default icon',
      TitlePlaceholder: 'Add title...',
      YourLinksLabel: 'Title and description for \'Your links\'',
      ShowHideGroupName: 'Hide/show',
      HideYourLinksLabel: 'Hide \'Your links\'',
      HideMandatoryLinksLabel: 'Hide \'Mandatory links\'',
      HideRecommendedLinksLabel: 'Hide \'Recommended links\'',
    },
    ActionRemoveMandatory: 'Mandatory links cannot be removed',
    AddToYourLinksLabel: 'Add {0} to your links',
    AddLabel: 'Add',
    ActiveLabel: 'Active',
    CancelLabel: 'Cancel',
    CategoryLabel: 'Category',
    CategoryPlaceholder: 'Optional category...',
    CreateSharedLinkLabel: 'Create link',
    EditorSectionDescription: 'This section is only visible to users who can add items to the EditorLinks list. Use it to manage links without opening the list directly.',
    EditorSectionLabel: 'Editor tools',
    EditorValidationLabel: 'Please fill in title and URL before saving.',
    IconLabel: 'Link icon',
    IconButtonLabel: 'Select icon',
    IconSearchLabel: 'Search icons',
    IconSearchPlaceholder: 'Search Fluent UI icons...',
    LoadingLabel: 'Loading links',
    MandatoryOptionLabel: 'Mandatory for everyone',
    MandatoryLinksLabel: 'Mandatory links',
    MandatoryLinksDescription: 'These links are mandatory for everyone, they cannot be removed or changed.',
    NewLinkLabel: 'Add personal link',
    NewSharedLinkLabel: 'Add link',
    NoIconsFoundLabel: 'No icons match your search.',
    NoCategoryLabel: 'No category',
    PersonalLinkNoticeLabel: 'Personal links are only visible to you.',
    PriorityLabel: 'Priority',
    PriorityPlaceholder: '1000',
    RemoveFromYourLinksLabel: 'Remove {0} from your links',
    RecommendedLinksLabel: 'Recommended links',
    RecommendedLinksDescription: 'These links are recommended for you, you can add them to your links (by clicking the + button).',
    SaveErrorLabel: 'Error: something went wrong saving your links.',
    SaveOkLabel: 'Your links was saved succesfully.',
    SaveYourLinksLabel: 'Save your links',
    SelectedIconLabel: 'Selected icon: ',
    TitleLabel: 'Title',
    TitlePlaceholder: 'Add link title here...',
    UseDefaultIconLabel: 'Use default icon',
    UrlLabel: 'URL',
    UrlPlaceholder: 'Add your link URL here...',
    UrlValidationLabel: 'Please add a proper URL.',
    YourLinksLabel: 'Your links',
    YourLinksDescription: 'Here you can add and manage personal links that only you can see. To remove a link, click the - button.'
  }
})
