define([], function () {
  return {
    PropertyPane: {
      AdvancedGroupName: 'Advanced',
      CategoryTitleFieldLabel: 'Group by category title',
      DefaultIconLabel: 'Default icon',
      DescriptionPlaceholder: 'Add description...',
      GeneralGroupName: 'General',
      GroupByCategoryLabel: 'Group by category',
      HeaderDescription: 'Configuration of the web part',
      MandatoryLinksLabel: 'Title and description for \'Mandatory links\'',
      RecommendedLinksLabel: 'Title and description for \'Recommended links\'',
      SelectDefaultIconLabel: 'Select default icon',
      TitlePlaceholder: 'Add title...',
      YourLinksLabel: 'Title and description for \'Your links\'',
      ShowHideGroupName: 'Hide/show',
      HideYourLinksLabel: 'Hide \'Your links\'',
      HideMandatoryLinksLabel: 'Hide \'Mandatory links\'',
      HideRecommendedLinksLabel: 'Hide \'Recommended links\'',
    },
    ActionRemoveMandatory: 'Mandatory links cannot be removed',
    AddToYourLinksLabel: 'Add {0} to your links',
    AddLabel: 'Add',
    CancelLabel: 'Cancel',
    IconLabel: 'Link icon',
    IconButtonLabel: 'Select icon',
    IconSearchLabel: 'Search icons',
    IconSearchPlaceholder: 'Search Fluent UI icons...',
    LoadingLabel: 'Loading links',
    MandatoryLinksLabel: 'Mandatory links',
    MandatoryLinksDescription: 'These links are mandatory for everyone, they cannot be removed or changed.',
    NewLinkLabel: 'Add new link',
    NoIconsFoundLabel: 'No icons match your search.',
    NoCategoryLabel: 'No category',
    RemoveFromYourLinksLabel: 'Remove {0} from your links',
    RecommendedLinksLabel: 'Recommended links',
    RecommendedLinksDescription: 'These links are recommended for you, you can add them to your links (by clicking the + button).',
    SaveErrorLabel: 'Error: something went wrong saving your links.',
    SaveOkLabel: 'Your links was saved succesfully.',
    SaveYourLinksLabel: 'Save your links',
    SelectedIconLabel: 'Selected icon: ',
    TitleLabel: 'Title',
    TitlePlaceholder: 'Add link title here...',
    UseDefaultIconLabel: 'Use default icon',
    UrlLabel: 'URL',
    UrlPlaceholder: 'Add your link URL here...',
    UrlValidationLabel: 'Please add a proper URL.',
    YourLinksLabel: 'Your links',
    YourLinksDescription: 'Here you can add and manage your own links. To remove a link, clikc the - button.'
  }
})
