define([], function () {
  return {
    PropertyPane: {
      AdvancedGroupName: 'Avansert',
      CategoryTitleFieldLabel: 'Overskrift grupperte lenker',
      DefaultIconLabel: 'Standard ikon',
      DescriptionPlaceholder: 'Angi beskrivelse...',
      GeneralGroupName: 'Generelt',
      GroupByCategoryLabel: 'Grupper etter kategorier',
      HeaderDescription:  'Konfigurasjon av webdelen',
      MandatoryLinksLabel: 'Tittel og beskrivelse for \'Obligatoriske lenker\'',
      RecommendedLinksLabel: 'Tittel og beskrivelse for \'Anbefalte lenker\'',
      SelectDefaultIconLabel: 'Velg standard ikon',
      TitlePlaceholder: 'Angi tittel...',
      YourLinksLabel: 'Tittel og beskrivelse for \'Dine lenker\'',
      ShowHideGroupName: 'Skjul/vis',
      HideYourLinksLabel: 'Skjul \'Dine lenker\'',
      HideMandatoryLinksLabel: 'Skjul \'Obligatoriske lenker\'',
      HideRecommendedLinksLabel: 'Skjul \'Anbefalte lenker\'',
    },
    ActionRemoveMandatory: 'Obligatoriske lenker kan ikke fjernes',
    AddToYourLinksLabel: 'Legg til {0} i dine lenker',
    AddLabel: 'Legg til',
    ActiveLabel: 'Aktiv',
    CancelLabel: 'Avbryt',
    CategoryLabel: 'Kategori',
    CategoryPlaceholder: 'Valgfri kategori...',
    CreateSharedLinkLabel: 'Opprett lenke',
    EditorSectionDescription: 'Denne seksjonen vises bare for brukere som kan legge til elementer i EditorLinks-listen. Bruk den for å administrere lenker uten å åpne listen direkte.',
    EditorSectionLabel: 'Redaktørverktøy',
    EditorValidationLabel: 'Fyll ut tittel og URL før du lagrer.',
    IconLabel: 'Ikon for lenke',
    IconButtonLabel: 'Velg ikon',
    IconSearchLabel: 'Søk i ikoner',
    IconSearchPlaceholder: 'Søk etter Fluent UI-ikoner...',
    LoadingLabel: 'Laster inn lenker',
    MandatoryOptionLabel: 'Obligatorisk for alle',
    MandatoryLinksLabel: 'Obligatoriske lenker',
    MandatoryLinksDescription: 'Her er lenker som er obligatoriske for alle, disse kan ikke fjernes eller endres.',
    NewLinkLabel: 'Legg til personlig lenke',
    NewSharedLinkLabel: 'Legg til lenke',
    NoIconsFoundLabel: 'Fant ingen ikoner som passer søket.',
    NoCategoryLabel: 'Ingen kategori',
    PersonalLinkNoticeLabel: 'Personlige lenker er bare synlige for deg.',
    PriorityLabel: 'Prioritet',
    PriorityPlaceholder: '1000',
    RemoveFromYourLinksLabel: 'Fjern {0} fra dine lenker',
    RecommendedLinksLabel: 'Anbefalte lenker',
    RecommendedLinksDescription: 'Her er lenker som er anbefalt for deg, disse kan du legge til dine lenker (ved å trykke på + knappen).',
    SaveErrorLabel: 'Feil: noe gikk galt under lagring av dine lenker.',
    SaveOkLabel: 'Dine lenker er lagret.',
    SaveYourLinksLabel: 'Lagre dine lenker',
    SelectedIconLabel: 'Valgt ikon: ',
    TitleLabel: 'Tittel',
    TitlePlaceholder: 'Angi tittel for lenken her...',
    UseDefaultIconLabel: 'Bruk standardikon',
    UrlLabel: 'URL',
    UrlValidationLabel: 'Legg til en gyldig URL for lenken, inkludert http(s)://',
    UrlPlaceholder: 'Angi URL for lenken her...',
    YourLinksLabel: 'Dine lenker',
    YourLinksDescription: 'Her kan du legge til og administrere personlige lenker som bare du ser. For å fjerne en lenke, trykk på - knappen.'
  }
})
