define([], function () {
  return {
    PropertyPane: {
      AdvancedGroupName: 'Advanced',
      AllLinksTextFieldDescription: 'Here you can add your own text for the link in the top right corner of the web part.',
      AllLinksTextFieldLabel: 'Text for \'See all\' link',
      AllLinksUrlLabel: 'Link to \'All Links\' page',
      ButtonAppearanceLabel: 'Button appearance',
      DefaultIconLabel: 'Default icon',
      DescriptionFieldDescription: 'Description of the web part, shown when clicking the info icon next to the title.',
      DescriptionFieldLabel: 'Description',
      GeneralGroupName: 'General',
      GlobalConfigurationUrlLabel: 'Global configuration',
      GlobalConfigurationUrlDescription: 'Here you can add a global configuration. Add the absolute URL to the site you want to fetch links from. This site must contain the lists \'Editor links\' and \'Favourite links\' for this to work. Example: https://contoso.sharepoint.com or https://contoso.sharepoint.com/sites/contoso',
      GroupByCategoryLabel: 'Group by category',
      HeaderDescription: 'Configuration of the web part',
      HideHeaderLabel: 'Hide header',
      HideShowAllLabel: 'Hide \'Show all\'-link',
      HideTitleLabel: 'Hide title',
      IconSizeLabel: 'Icon size',
      IconsOnlyLabel: 'Show icons only',
      LineHeightLabel: 'Line height (pixels)',
      GapSizeLabel: 'Gap size between buttons (pixels)',
      LinkClickWebHookLabel: 'Webhook for link click',
      RenderShadowLabel: 'Render shadow',
      ResponsiveButtonsLabel: 'Responsive buttons (wrapping)',
      SelectDefaultIconLabel: 'Select default icon',
      ShowHideGroupName: 'Hide/show',
      StylingGroupName: 'Styling',
      TitleFieldDescription: 'Title shown in the header of the web part.',
      TitleFieldLabel: 'Title',
    },
    AllLinksLabel: 'See all',
    Description: 'Here is a collection of mandatory links and your own links at the bottom.',
    NoCategoryLabel: 'No category',
    Title: 'Your links'
  }
})
