define([], function () {
  return {
    PropertyPane: {
      AdvancedGroupName: 'Avansert',
      AllLinksTextFieldDescription: 'Her kan du angi egen tekst på lenken oppe til høyre i webdelen.',
      AllLinksTextFieldLabel: 'Tekst for \'Se alle\' lenken',
      AllLinksUrlLabel: 'Lenke til \'Alle lenker\'',
      ButtonAppearanceLabel: 'Utseende på knapper',
      ButtonAppearanceSecondaryLabel: 'Sekundær',
      ButtonAppearancePrimaryLabel: 'Primær',
      ButtonAppearanceOutlineLabel: 'Kontur',
      ButtonAppearanceSubtleLabel: 'Subtil',
      ButtonAppearanceTransparentLabel: 'Transparent',
      DefaultIconLabel: 'Standard ikon',
      DescriptionFieldDescription: 'Beskrivelse av webdelen, dukker opp ved trykk på info-ikonet ved siden av tittel.',
      DescriptionFieldLabel: 'Beskrivelse',
      GeneralGroupName: 'Generelt',
      GlobalConfigurationUrlLabel: 'Global konfigurasjon',
      GlobalConfigurationUrlDescription: 'Her kan du angi en global konfigurasjon. Angi absolutt URL til området du ønsker å hente lenker fra. Dette området må inneholde listene \'Anbefalte lenker\' og \'Personlige lenker\' for at dette skal fungere. Eksempel: https://contoso.sharepoint.com eller https://contoso.sharepoint.com/sites/contoso',
      GroupByCategoryLabel: 'Grupper etter kategorier',
      HeaderDescription: 'Konfigurasjon av webdelen',
      HideHeaderLabel: 'Skjul header',
      HideShowAllLabel: 'Skjul \'Vis alle\'-lenke',
      HideTitleLabel: 'Skjul tittel',
      IconSearchPlaceholder: 'Søk etter Fluent UI-ikoner...',
      IconSizeLabel: 'Ikonstørrelse',
      IconsOnlyLabel: 'Vis kun ikoner',
      LineHeightLabel: 'Linjehøyde (piksler)',
      GapSizeLabel: 'Avstand mellom knapper (piksler)',
      LinkClickWebHookLabel: 'Webhook for lenkeklikk',
      NoIconsFoundLabel: 'Fant ingen ikoner som passer søket.',
      RenderShadowLabel: 'Vis skygge',
      ResponsiveButtonsLabel: 'Responsive knapper (wrapping)',
      SelectedIconLabel: 'Valgt ikon:',
      SelectDefaultIconLabel: 'Velg standard ikon',
      ShowHideGroupName: 'Skjul/vis',
      StylingGroupName: 'Stil og utforming',
      TitleFieldDescription: 'Tittel som vises i headeren på webdelen.',
      TitleFieldLabel: 'Tittel',
    },
    AllLinksLabel: 'Se alle',
    CategoryFallbackLabel: 'Dine lenker',
    Description: 'Her er en samling av obligatoriske lenker og dine egne lenker nederst.',
    NoCategoryLabel: 'Ingen kategori',
    Title: 'Dine lenker'
  }
})
