define([], function () {
  return {
    "Property_PropertyPaneDescription": "Show tiles from a selected list.",
    "Property_BasicGroupName": "Settings",
    "Property_Count_Label": "Number of elements",
    "Property_ImageWidth_Label": "Tile width",
    "Property_ImageHeight_Label": "Tile height",
    "Property_TextPadding_Label": "Text padding",
    "Property_Description_Label": "Description Field",
    "Property_Description_Description": "Internal name of field containing description (Single line of text).",
    "Property_BackgroundImage_Label": "Background image Field",
    "Property_BackgroundImage_Description": "Internal name of field containing background image url (Hyperlink).",
    "Property_FallbackImageUrl_Label": "Fallback image",
    "Property_FallbackImageUrl_Description": "Link to a fallback image.",
    "Property_NewTab_Label": "Field for 'Open in new tab'",
    "Property_NewTab_Description": "Internal name of a 'Yes/No' field (Yes/No).",
    "Property_Link_Label": "URL Field",
    "Property_Link_Description": "Internal name of field containing URL value (Hyperlink).",
    "Property_OrderBy_Label": "Order Field",
    "Property_OrderBy_Description": "Internal name of field containing the sort order (Date/Number/Single line of text).",
    "Property_TileType_Label": "Tile type",
    "Property_TileChoiceField_Label": "Choice field",
    "Property_List_Label": "List",
    "Property_AdvancedSettings_OffText": "Show",
    "Property_AdvancedSettings_OnText": "Hide",
    "Property_AdvancedSettings_Label": "More settings",
    "View_NoOptionValue": "<None>",
    "View_EmptyPlaceholder_Label": 'Edit Web Part',
    "View_EmptyPlaceholder_Description": "Property 'List' is not yet configured.",
    "View_EmptyPlaceholder_Button": 'Edit',
  }
});